# the fixed length of the message type prefix in the protocol
MESSAGE_TYPE_LENGTH = 3

# messages types
HANDSHAKE_MSG_TYPE = "HSK"

MENU_ITEMS_BATCH_MSG_TYPE = "MIT"
STORES_BATCH_MSG_TYPE = "STR"
TRANSACTION_ITEMS_BATCH_MSG_TYPE = "TIT"
TRANSACTIONS_BATCH_MSG_TYPE = "TRN"
USERS_BATCH_MSG_TYPE = "USR"

QUERY_RESULT_1X_MSG_TYPE = "Q1X"
QUERY_RESULT_21_MSG_TYPE = "Q21"
QUERY_RESULT_22_MSG_TYPE = "Q22"
QUERY_RESULT_3X_MSG_TYPE = "Q3X"
QUERY_RESULT_4X_MSG_TYPE = "Q4X"

EOF_MSG_TYPE = "EOF"

# delimiters & separators
METADATA_DELIMITER = "|"
METADATA_SEPARATOR = ":"

MSG_START_DELIMITER = "["
MSG_END_DELIMITER = "]"

BATCH_START_DELIMITER = "{"
BATCH_END_DELIMITER = "}"
BATCH_ITEM_SEPARATOR = ";"
BATCH_ITEM_FIELD_SEPARATOR = ","

# payload
ALL_QUERIES = "Q1X;Q21;Q22;Q3X;Q4X"