FROM python:3.13-slim

# WORKDIR /app

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     iputils-ping ca-certificates tzdata \
#     && rm -rf /var/lib/apt/lists/*

# COPY requirements.txt /app/requirements.txt
# RUN pip install --no-cache-dir --upgrade pip \
#     && pip install --no-cache-dir -r /app/requirements.txt

# COPY app /app/app
# COPY scripts/entrypoint.sh /app/entrypoint.sh
# RUN chmod +x /app/entrypoint.sh

# ENV PYTHONUNBUFFERED=1

# ENTRYPOINT ["/app/entrypoint.sh"]
